npm install -g node-static
npm install -g nodemon
npm install -g coffee-script
npm install -g grunt-cli
npm install -g gulp
npm install -g bower
npm install -g less
npm install -g mocha
npm install -g karma-cli
npm install -g yo
npm install -g compass