npm install -g coffee-script
npm install -g cordova
npm install -g ios-deploy
npm install -g ionic
npm install -g ios-sim
npm install -g yo
npm install -g generator-angular
npm install -g generator-angular-fullstack
npm install -g grunt-cli
npm install -g bower
npm install -g gulp
npm install -g less
npm install -g mocha
npm install -g node-static
npm install -g nodemon
npm install -g azure-cli
npm install -g bkts
npm install -g protractor
npm install -g karma-cli
npm install -g shrinkwrap
